theme: jekyll-theme-minimal
#theme: jekyll-theme-cayman
#theme: jekyll-theme-slate
#theme: jekyll-theme-architect
#theme: jekyll-theme-leap-day

kramdown:
  input: GFM
  math_engine: mathjax # you can also set this field to 'katex'
